blank_issues_enabled: false
contact_links:
  - name: Feedback
    url: https://tools.tinykite.co/feedback
    about: "Share feedback or product ideas."
  - name: Discussions
    url: https://github.com/tinykite-co/tinykite-tools/discussions
    about: "Ask questions and discuss ideas."
